from pbx_gs_python_utils.utils.Dev import Dev

from oss_bot.api.API_OSS_Bot import API_OSS_Bot


class Slack_Handler:

    def run(self,data):
        result = None
        if "challenge" in data:              # required for Slack event check
            return data.get("challenge")
        team_id = data.get('team_id')
        if data.get('event'):
            slack_event = data.get('event')
            if ("bot_id" in slack_event) is False:                      # this happens when the data was generated by an bot
                result = API_OSS_Bot().process_event(slack_event)          # add a `return` here to see message in test
        #elif data.get('body'):
        #    result = API_OSS_Bot(team_id).process_posted_body(data.get('body'))

        if team_id is None:                                             # to help with unit tests
            return result
        return "200 OK"
